version: 2

updates:
  - package-ecosystem: pip
    directory: /infra/lambdas/orchestrator
    schedule:
      interval: daily
      time: "08:00"
      timezone: America/Sao_Paulo
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies
      - python

  - package-ecosystem: docker
    directory: /infra/lambdas/orchestrator
    schedule:
      interval: daily
      time: "08:00"
      timezone: America/Sao_Paulo
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies
      - docker

  - package-ecosystem: npm
    directory: /scripts
    schedule:
      interval: daily
      time: "08:00"
      timezone: America/Sao_Paulo
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies
      - javascript

  - package-ecosystem: terraform
    directory: /infra/terraform
    schedule:
      interval: daily
      time: "08:00"
      timezone: America/Sao_Paulo
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies
      - terraform

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: America/Sao_Paulo
    commit-message:
      prefix: "chore(ci)"
    labels:
      - dependencies
      - github-actions
